name: Test Code

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  test-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Rust Stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
          
    - name: Install Rust Nightly Toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        target: wasm32-unknown-unknown
          
      # Steps taken from https://github.com/actions/cache/blob/master/examples.md#rust---cargo
    - name: Cache Dependencies & Build Outputs
      uses: actions/cache@v2.1.6
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Check Code
      uses: actions-rs/cargo@v1
      env:
        SKIP_WASM_BUILD: 1
      with:
        command: check
        args: --all-targets
        
    - name: Check Code
      run: cargo check

    - name: Test Code
      run: cargo test